name: klinik_cikidang_medika
description: Sistem Informasi Manajemen (SIM) Pelayanan Pasien, Rekam Medis, & Keuangan Klinik Pratama Cikidang Medika
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

flutter:
  uses-material-design: true

  # Registered Assets Specification
  assets:
    - src/assets/
    - src/assets/images/
    - src/assets/images/logo-full.png
    - src/assets/images/logo-emblem.png
    - src/assets/images/logo-square.png
    - src/assets/images/cikidang-medika-transparant.png
    - public/
    - public/assets/images/
    - public/assets/images/logo-full.png
    - public/assets/images/logo-emblem.png
    - public/assets/images/logo-square.png
    - public/assets/images/cikidang-medika-transparant.png
    - public/logo.png
    - public/icon.png
    - public/favicon.ico
